const MAX_NAME_LENGTH: number = 255;
const DEFAULT_STUCK_MIGRATION_TIMEOUT_MINUTES: number = 30;
const MAX_STATUS_LENGTH: number = 20;
const DEFAULT_TABLE_NAME: string = "config_migrations";

export const CONFIG_MIGRATION_CONSTANT: {
 readonly DEFAULT_STUCK_MIGRATION_TIMEOUT_MINUTES: number;
 readonly DEFAULT_TABLE_NAME: string;
 readonly MAX_NAME_LENGTH: number;
 readonly MAX_STATUS_LENGTH: number;
} = {
 DEFAULT_STUCK_MIGRATION_TIMEOUT_MINUTES: DEFAULT_STUCK_MIGRATION_TIMEOUT_MINUTES,
 DEFAULT_TABLE_NAME: DEFAULT_TABLE_NAME,
 MAX_NAME_LENGTH: MAX_NAME_LENGTH,
 MAX_STATUS_LENGTH: MAX_STATUS_LENGTH,
} as const;
